### ISSUE TITLE
Add additional EMIS tables to the EMIS backend

### ISSUE THREAD

**Issue by rebkwok** [opensafely-core/ehrql#1526] opened 2023-08-23 16:59 UTC
Currently we have `patients`, `clinical_events`, `medications`, `ons_deaths`; there will be others needed for cohort-extractor parity.

This will also involve adding some test framework and tests for the emis backend, similar to the ones in tests/integration/backends for tpp

**Comment by inglesp** [comment] 2023-10-31 10:20
Duplicate of #797.

**Closed by inglesp** 2023-10-31 10:20 UTC
Labels: cohortextractor-parity
