### ISSUE TITLE
Make it clear exactly which patients are in each backend

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1630] opened 2023-09-28 13:59 UTC
This should include notes on things like [full GMS registrations](https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/#practice_registrations) and T1OO issues as appropriate.

It's an open question where exactly this lives. Maybe in the backend docs? e.g.
https://docs.opensafely.org/ehrql/reference/backends/#tpp

Maybe in the primary schema for each backend e.g.
https://docs.opensafely.org/ehrql/reference/schemas/beta.tpp/

Related slack thread:
https://bennettoxford.slack.com/archives/C05CG8W1GRL/p1695906402505959

**Comment by inglesp** [comment] 2023-10-31 10:24
Duplicate of #1450.

**Closed by inglesp** 2023-10-31 10:24 UTC
Labels: documentation
