### ISSUE TITLE
Drop `is_between()` DateSeries method

### ISSUE THREAD

**Issue by evansd** [opensafely-core/ehrql#1188] opened 2023-04-05 15:25 UTC
The `is_between()` method is the exclusive complement to the inclusive `is_on_or_between()` and was added (I think) just for the sake of consistency because the other inclusive methods (`is_on_or_before()` and `is_on_or_after()`) have exclusive complements.

But as @wjchulme has pointed out, the potential for confusion here is quite high as it would be very easy for a casual reader to assume that it was inclusive. And on top of that, an exclusive date range function doesn't seem all that useful.

Slack thread here:
https://bennettoxford.slack.com/archives/C04DVD1UQC9/p1680707203503939

**Comment by Jongmassey** [comment] 2023-04-19 09:03
Inspired by a recent sql query in a database notebook migration by @iaindillingham which forewent `BETWEEN` in favour of explicit comparison operators, I like the explicit clarity of these and should we just be using these instead?

**Comment by milanwiedemann** [comment] 2023-07-03 08:18
code search suggests that this method is not used in ehrQL studies https://github.com/search?q=org%3Aopensafely+%27is_between%28%29%27&type=code

**Comment by evansd** [comment] 2023-07-03 12:02
@milanwiedemann I don't think that search is correct because you're searching for the literal string `is_between()` (i.e. with no arguments) which is never going to be found.

If you search for `is_between` you do get some matches:
https://github.com/search?q=org%3Aopensafely+%22is_between%22&type=code

I think we'll need to contact the study authors and check what they actually intended in these cases because I suspect they really meant to use `is_on_or_between` anyway.

**Comment by milanwiedemann** [comment] 2023-07-04 10:26
Right! Of course, there are two repositories that use the `is_between()` method. Both studies are led by [Alasdair Henderson](https://github.com/hendersonad). I'll draft a message to ask what they intended and then review #1370 and their study code based on their response.

1. [opensafely/shielding-evaluation](https://github.com/opensafely/shielding-evaluation)
    - [ ] [‎analysis/databuilder_definition.py](https://github.com/opensafely/shielding-evaluation/blob/f732b81b0c515743c78480ea5143a6dbf66dea2c/analysis/databuilder_definition.py#L67)
1. [opensafely/openprompt-vaccine-long-covid](https://github.com/opensafely/openprompt-vaccine-long-covid)
    - [ ] [‎analysis/variable_lib.py](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/79490807e93afc9e45387bfc66d633d301164f0b/analysis/variable_lib.py#L140)
    - [ ] [analysis/datasets.py](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/79490807e93afc9e45387bfc66d633d301164f0b/analysis/datasets.py#L284)
    - [ ] [analysis/dataset_definition_longcovid_prevaccine.py‎](https://github.com/opensafely/openprompt-vaccine-long-covid/blob/79490807e93afc9e45387bfc66d633d301164f0b/analysis/dataset_definition_longcovid_prevaccine.py#L118)

**Comment by milanwiedemann** [comment] 2023-07-05 15:14
the study author has confirmed that they did not intend to include the start and end date. so we need suggest a code change that is identical to the `is_between()` method

**Comment by milanwiedemann** [comment] 2023-07-10 07:00
following discussion on slack with @evansd and @inglesp we have decided to keep the functionality because it is used in some studies. but we will rename `is_between()` to `is_between_but_not_on()` so it is less ambiguous and follows the naming convention of the similar method `is_on_or_between()`. this is the workflow suggested by Dave:

- [ ] release new version that adds the new name `is_between_but_not_on()` but doesn't yet remove the old one `is_between()`
- [ ] update any studies using the old name (see [here](https://github.com/opensafely-core/ehrql/issues/1188#issuecomment-1619980608)) to use the new one.
- [ ] finally make a new release which removes the old name

**Comment by milanwiedemann** [comment] 2023-07-10 15:51
only #1405 was merged, #1406 still missing

**Closed** 2023-07-11 10:13 UTC
